resources:
  limits:
    cpus: 2.0
    memory: 4096

TZ: America/Toronto

npmplus:
  additional_envs: []

network:
  web_port:
    bind_mode: published
    port_number: 10081

  http_port:
    bind_mode: published
    port_number: 10080

  https_port:
    bind_mode: published
    port_number: 10443

  additional_ports: []

run_as:
  user: 1001
  group: 1001

ix_volumes:
  data: /opt/tests/mnt/data

storage:
  data:
    type: ix_volume
    ix_volume_config:
      dataset_name: data
      create_host_path: true
      
  additional_storage:
    - type: anonymous
      mount_path: /scratchpad
      volume_config:
        nocopy: true
